export const SPECIFIC_CHARACTERS = [
  "Zeus",
  "Athena",
  "Hestia",
  "Apollo",
  "Artemis",
  "Poseidon",
  "Hades",
  "Demeter",
  "Aphrodite",
  "Hera",
  "Dionysus",
  "Ares",
  "Hephaestus",
  "Persephone",
  "Hermes",
  "Nyx",
  "Hypnos",
  "Thanatos",
  "Morpheus",
  "Asclepius",
];

export const CUSTOM_SPRITES = [
    Zeus: "../../assets/characters/zeus.png",
    Athena: "../../assets/characters/athena.png",
    Hestia: "../../assets/characters/hestia.png",
    Apollo: "../../assets/characters/apollo.png",
    Artemis: "../../assets/characters/artemis.png",
    Poseidon: "../../assets/characters/poseidon.png",
    Hades: "../../assets/characters/hades.png",
    Demeter: "../../assets/characters/demeter.png",
    Aphrodite: "../../assets/characters/aphrodite.png",
    Hera: "../../assets/characters/hera.png",
    Dionysus: "../../assets/characters/dionysus.png",
    Ares: "../../assets/characters/ares.png",
    Hephaestus: "../../assets/characters/hephaestus.png",
    Persephone: "../../assets/characters/persephone.png",
    Hermes: "../../assets/characters/hermes.png",
    Nyx: "../../assets/characters/nyx.png",
    Hypnos: "../../assets/characters/hypnos.png",
    Thanatos: "../../assets/characters/thanatos.png",
    Morpheus: "../../assets/characters/morpheus.png",
    Asclepius: "../../assets/characters/asclepius.png",
]