export const SPECIFIC_CHARACTERS = [
  "Zeus",
  "Athena",
  "Hestia",
  "Apollo",
  "Artemis",
  "Poseidon",
  "Hades",
  "Demeter",
  "Aphrodite",
  "Hera",
  "Dionysus",
  "Ares",
  "Hephaestus",
  "Persephone",
  "Hermes",
  "Nyx",
  "Hypnos",
  "Thanatos",
  "Morpheus",
  "Asclepius",
];

export const CUSTOM_SPRITES = {
  Zeus: "../../assets/characters/zeus.png",
  Athena: "../../assets/characters/athena.png",
  Hestia: "../../assets/characters/hestia.png",
  Apollo: "../../assets/characters/apollo.png",
  Artemis: "../../assets/characters/artemis.png",
  Poseidon: "../../assets/characters/poseidon.png",
  Hades: "../../assets/characters/hades.png",
  Demeter: "../../assets/characters/demeter.png",
  Aphrodite: "../../assets/characters/aphrodite.png",
  Hera: "../../assets/characters/hera.png",
  Dionysus: "../../assets/characters/dionysus.png",
  Ares: "../../assets/characters/ares.png",
  Hephaestus: "../../assets/characters/hephaestus.png",
  Persephone: "../../assets/characters/persephone.png",
  Hermes: "../../assets/characters/hermes.png",
  Nyx: "../../assets/characters/nyx.png",
  Hypnos: "../../assets/characters/hypnos.png",
  Thanatos: "../../assets/characters/thanatos.png",
  Morpheus: "../../assets/characters/morpheus.png",
  Asclepius: "../../assets/characters/asclepius.png",
};

export const CUSTOM_STATS = {
  Zeus: {
    tier: "Tier 1",
    tierName: "The Big Three",
    hp: 15000,
    attack: 110,
    defense: 95,
    speed: 120,
    power: 150,
    resilience: 100,
    stamina: 110,
    currenthp: 15000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Sky/Lightning",
    masteryDesc: "+25% electric damage",
    specialTrait: "King's Wrath",
    traitDesc: "10% chance to smite enemy for bonus true damage",
  },
  Athena: {
    tier: "Tier 3",
    tierName: "Middle Olympians",
    hp: 14000,
    attack: 100,
    defense: 120,
    speed: 105,
    power: 115,
    resilience: 130,
    stamina: 110,
    currenthp: 14000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Wisdom/Strategy",
    masteryDesc: "Team defense +10%",
    specialTrait: "Perfect Counter",
    traitDesc: "30% chance to auto-block melee attacks",
  },
  Hestia: {
    tier: "Tier 2",
    tierName: "Elder Olympians",
    hp: 14000,
    attack: 80,
    defense: 120,
    speed: 85,
    power: 110,
    resilience: 130,
    stamina: 150,
    currenthp: 14000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Hearth Fire",
    masteryDesc: "Healing + burn damage boosts",
    specialTrait: "Warmth of Home",
    traitDesc: "Grants minor healing each turn to allies",
  },
  Apollo: {
    tier: "Tier 3",
    tierName: "Middle Olympians",
    hp: 13000,
    attack: 95,
    defense: 80,
    speed: 125,
    power: 140,
    resilience: 90,
    stamina: 110,
    currenthp: 13000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Light/Music",
    masteryDesc: "+20% light damage",
    specialTrait: "Prophetic Strike",
    traitDesc: "First attack always crits",
  },
  Artemis: {
    tier: "Tier 3",
    tierName: "Middle Olympians",
    hp: 12000,
    attack: 110,
    defense: 85,
    speed: 135,
    power: 105,
    resilience: 95,
    stamina: 115,
    currenthp: 12000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Moon/Hunt",
    masteryDesc: "+25% crit chance on moving targets",
    specialTrait: "Hunter's Mark",
    traitDesc: "First hit on any enemy does bonus damage",
  },
  Poseidon: {
    tier: "Tier 1",
    tierName: "The Big Three",
    hp: 16000,
    attack: 115,
    defense: 110,
    speed: 100,
    power: 140,
    resilience: 120,
    stamina: 115,
    currenthp: 16000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Sea",
    masteryDesc: "+20% water damage, +30% damage when fighting near water",
    specialTrait: "Tidal Fury",
    traitDesc: "Consecutive attacks increase in damage",
  },
  Hades: {
    tier: "Tier 1",
    tierName: "The Big Three",
    hp: 17000,
    attack: 95,
    defense: 140,
    speed: 80,
    power: 130,
    resilience: 150,
    stamina: 90,
    currenthp: 17000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Underworld",
    masteryDesc: "+30% damage vs undead/fear/sleep",
    specialTrait: "Soul Drain",
    traitDesc: "Steals HP on hit (5% of damage dealt)",
  },
  Demeter: {
    tier: "Tier 2",
    tierName: "Elder Olympians",
    hp: 14500,
    attack: 85,
    defense: 115,
    speed: 80,
    power: 125,
    resilience: 110,
    stamina: 130,
    currenthp: 14500,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Harvest",
    masteryDesc: "+20% regeneration, +25% poison resistance",
    specialTrait: "Fallow Curse",
    traitDesc: "Can reduce enemy Attack temporarily",
  },
  Aphrodite: {
    tier: "Tier 4",
    tierName: "Younger Olympians",
    hp: 12000,
    attack: 70,
    defense: 80,
    speed: 110,
    power: 115,
    resilience: 85,
    stamina: 100,
    currenthp: 12000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Charm",
    masteryDesc: "25% chance enemies skip turn",
    specialTrait: "Irresistible Aura",
    traitDesc: "First strike against her does half damage",
  },
  Hera: {
    tier: "Tier 2",
    tierName: "Elder Olympians",
    hp: 15000,
    attack: 90,
    defense: 120,
    speed: 90,
    power: 125,
    resilience: 120,
    stamina: 120,
    currenthp: 15000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Queenship",
    masteryDesc: "Team buffs stronger by 20%",
    specialTrait: "Divine Authority",
    traitDesc: "Immune to charm and can reflect debuffs",
  },
  Dionysus: {
    tier: "Tier 4",
    tierName: "Younger Olympians",
    hp: 13000,
    attack: 85,
    defense: 85,
    speed: 95,
    power: 120,
    resilience: 90,
    stamina: 130,
    currenthp: 13000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Madness",
    masteryDesc: "Debuffs 20% stronger",
    specialTrait: "Ecstatic Frenzy",
    traitDesc: "Random buffs each turn",
  },
  Ares: {
    tier: "Tier 3",
    tierName: "Middle Olympians",
    hp: 15000,
    attack: 145,
    defense: 100,
    speed: 110,
    power: 95,
    resilience: 100,
    stamina: 120,
    currenthp: 15000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "War",
    masteryDesc: "+15% damage per hit taken",
    specialTrait: "Bloodlust",
    traitDesc: "Attack increases each time he deals damage",
  },
  Hephaestus: {
    tier: "Tier 4",
    tierName: "Younger Olympians",
    hp: 14000,
    attack: 130,
    defense: 135,
    speed: 65,
    power: 115,
    resilience: 110,
    stamina: 100,
    currenthp: 14000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Forge",
    masteryDesc: "+20% damage with crafted weapons",
    specialTrait: "Molten Skin",
    traitDesc: "Reduces fire damage to 0",
  },
  Persephone: {
    tier: "Tier 5",
    tierName: "Minor Gods",
    hp: 12500,
    attack: 75,
    defense: 90,
    speed: 95,
    power: 110,
    resilience: 100,
    stamina: 120,
    currenthp: 12500,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Spring/Underworld",
    masteryDesc: "Alternating form bonuses",
    specialTrait: "Dual Aspect",
    traitDesc: "Stats change each season (Spring boost/Underworld boost)",
  },
  Hermes: {
    tier: "Tier 4",
    tierName: "Younger Olympians",
    hp: 11500,
    attack: 90,
    defense: 75,
    speed: 160,
    power: 100,
    resilience: 80,
    stamina: 140,
    currenthp: 11500,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Speed/Trickery",
    masteryDesc: "+20% dodge",
    specialTrait: "Swift Step",
    traitDesc: "Gains an extra small action each turn",
  },
  Nyx: {
    tier: "Tier 0",
    tierName: "Primordial",
    hp: 17000,
    attack: 100,
    defense: 120,
    speed: 110,
    power: 160,
    resilience: 140,
    stamina: 120,
    currenthp: 17000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Night/Void",
    masteryDesc: "+30% shadow damage, +20% evasion in darkness",
    specialTrait: "Primordial Aura",
    traitDesc: "Debuffs have double duration; immune to Sleep and Fear",
  },
  Hypnos: {
    tier: "Tier 5",
    tierName: "Minor Gods",
    hp: 11000,
    attack: 60,
    defense: 75,
    speed: 70,
    power: 120,
    resilience: 95,
    stamina: 130,
    currenthp: 11000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Sleep",
    masteryDesc: "+30% chance to inflict sleep",
    specialTrait: "Dream Veil",
    traitDesc: "20% damage reduction from melee",
  },
  Thanatos: {
    tier: "Tier 5",
    tierName: "Minor Gods",
    hp: 11500,
    attack: 90,
    defense: 85,
    speed: 120,
    power: 100,
    resilience: 110,
    stamina: 100,
    currenthp: 11500,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Death",
    masteryDesc: "Kills low-HP enemies instantly",
    specialTrait: "Reaper's Touch",
    traitDesc: "Critical hits do double true damage",
  },
  Morpheus: {
    tier: "Tier 5",
    tierName: "Minor Gods",
    hp: 10500,
    attack: 70,
    defense: 80,
    speed: 100,
    power: 125,
    resilience: 85,
    stamina: 110,
    currenthp: 10500,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Dreams",
    masteryDesc: "Illusions reduce enemy accuracy",
    specialTrait: "Shifting Form",
    traitDesc: "15% chance to avoid attacks entirely",
  },
  Asclepius: {
    tier: "Tier 5",
    tierName: "Minor Gods",
    hp: 12000,
    attack: 50,
    defense: 85,
    speed: 90,
    power: 135,
    resilience: 110,
    stamina: 150,
    currenthp: 12000,
    buffs: [],
    debuffs: [],
    status: [],
    domainMastery: "Healing",
    masteryDesc: "+30% healing power",
    specialTrait: "Miracle Touch",
    traitDesc: "Once per battle revive ally to 30% HP",
  },
};
